# Generated by Django 4.2.20 on 2025-04-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='articles.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='accounts.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='accounts_ar_user_id_a38e28_idx'), models.Index(fields=['article', 'viewed_at'], name='accounts_ar_article_b3694e_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='accounts.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'liked_at'], name='accounts_ar_user_id_72624c_idx'), models.Index(fields=['article', 'liked_at'], name='accounts_ar_article_e5828e_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
